development:
  adapter: postgresql
  encoding: unicode
  database: voicey_development
  pool: 5
  username: johnathan
  password: 7898521c

test:
  adapter: postgresql
  encoding: unicode
  database: voicey_test
  pool: 5
  username: johnathan
  password: 7898521c


production:
  adapter: postgresql
  encoding: unicode
  database: voicey_production
  pool: 5
  username: johnathan
  password: 7898521c
